services:
  - type: web
    name: telegram-bot
    runtime: python
    buildCommand: ""
    startCommand: gunicorn wsgi:app
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        value: "TU_TOKEN_AQUI"
      - key: TELEGRAM_CHAT_ID
        value: "TU_CHAT_ID_AQUI"
